on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v6
        
      - name: Build project
        run: dotnet build RedRoverPuzzle.csproj --configuration Release
        
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: RedRoverPuzzle
          path: ./bin/Release/net10.0